apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 
namespace: argocd-prod 
bases: 
  - github.com/argoproj/argo-cd/manifests/ha/namespace-install?ref=v2.13.3
resources: 
  - resources/namespace.yaml

