apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata:
  name: argocd-prod
spec: 
  destination: 
    namespace: argocd-nonprod
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: trouble-shooting/initial-setup/argocd-prod
    repoURL: https://github.com/High10Hunter/ha-argocd-training.git 
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
